#!/bin/sh
'''exec' C:/Users/kibby/Files/invest-plugin-for-workshop/env/bin/python "$0" "$@"
' '''
import sys
from pint.pint_convert import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
